// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patililer.Data;

#nullable disable

namespace Patililer.Migrations
{
    [DbContext(typeof(PatililerDBContext))]
    [Migration("20230126125031_bir")]
    partial class bir
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patililer.Models.Siniflar.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Kullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Adres", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdresAcik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Hakkimizda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hakkimizdas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Aciklama = "Ücretsiz evcil hayvan sahiplendirme ilanlarına göz atabilir, bir canlı sahiplenebilirsin.Aradığın canlıyı bulamadıysan, arıyorum ilanı bırakabilirsin.Pet için eş arıyorsan, eş arıyorum ilanı ekleyebilirsin. Dikkat :Kimseye ödeme yapmayın,dolandırılma riski var! Bu site satış sitesi değildir.Size yakın şehirlerden elden satın almaya özen gösterin.",
                            FotoUrl = "dsds"
                        });
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Ilanlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlanImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ilanlars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Aciklama = "1.hayvan",
                            Baslik = "köpek",
                            Cinsiyet = "erkek",
                            IlanImage = "kdsk",
                            Tarih = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yas = 1
                        },
                        new
                        {
                            ID = 2,
                            Aciklama = "2.hayvan",
                            Baslik = "kedi",
                            Cinsiyet = "erkek",
                            IlanImage = "kdsk",
                            Tarih = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yas = 2
                        },
                        new
                        {
                            ID = 3,
                            Aciklama = "3.hayvan",
                            Baslik = "kedi",
                            Cinsiyet = "dişi",
                            IlanImage = "kdsk",
                            Tarih = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yas = 3
                        },
                        new
                        {
                            ID = 4,
                            Aciklama = "4.hayvan",
                            Baslik = "köpek",
                            Cinsiyet = "dişi",
                            IlanImage = "kdsk",
                            Tarih = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yas = 1
                        });
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Iletisim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Iletisims");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdSoyad = "xcx",
                            Konu = "fdf",
                            Mail = "dfd",
                            Mesaj = "fdf"
                        });
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Rolee", b =>
                {
                    b.Property<byte>("RoleeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoleeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleeID");

                    b.ToTable("rolees");

                    b.HasData(
                        new
                        {
                            RoleeID = (byte)1,
                            RoleeName = "Aday"
                        },
                        new
                        {
                            RoleeID = (byte)2,
                            RoleeName = "Uye"
                        },
                        new
                        {
                            RoleeID = (byte)3,
                            RoleeName = "Admin"
                        },
                        new
                        {
                            RoleeID = (byte)4,
                            RoleeName = "Supervisor"
                        });
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Userr", b =>
                {
                    b.Property<int>("UserrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserrID"));

                    b.Property<string>("Emaill")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Passwordd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("RoleeID")
                        .HasColumnType("tinyint");

                    b.HasKey("UserrID");

                    b.HasIndex("RoleeID");

                    b.ToTable("userrs");

                    b.HasData(
                        new
                        {
                            UserrID = 1,
                            Emaill = "aday@hotmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)1
                        },
                        new
                        {
                            UserrID = 2,
                            Emaill = "uye@hotmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)2
                        },
                        new
                        {
                            UserrID = 3,
                            Emaill = "admin@hotmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)3
                        },
                        new
                        {
                            UserrID = 4,
                            Emaill = "supervisor@hotmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)4
                        },
                        new
                        {
                            UserrID = 5,
                            Emaill = "uye2@hotmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)2
                        });
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Yorumlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("IlanlarID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IlanlarID");

                    b.ToTable("Yorumlars");
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Userr", b =>
                {
                    b.HasOne("Patililer.Models.Siniflar.Rolee", "Rolee")
                        .WithMany()
                        .HasForeignKey("RoleeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rolee");
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Yorumlar", b =>
                {
                    b.HasOne("Patililer.Models.Siniflar.Ilanlar", "Ilanlar")
                        .WithMany("Yorumlars")
                        .HasForeignKey("IlanlarID");

                    b.Navigation("Ilanlar");
                });

            modelBuilder.Entity("Patililer.Models.Siniflar.Ilanlar", b =>
                {
                    b.Navigation("Yorumlars");
                });
#pragma warning restore 612, 618
        }
    }
}
